// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { Counter, CounterTableId } from "./tables/Counter.sol";
import { GridBolid, GridBolidData, GridBolidTableId } from "./tables/GridBolid.sol";
import { OwnerList, OwnerListTableId } from "./tables/OwnerList.sol";
import { GridTrack, GridTrackData, GridTrackTableId } from "./tables/GridTrack.sol";
import { RaceRegister, RaceRegisterData, RaceRegisterTableId } from "./tables/RaceRegister.sol";
import { FizState, FizStateData, FizStateTableId } from "./tables/FizState.sol";
