// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */
enum TrackProp {
  Curb1,
  Curb2,
  Curb3,
  Road1,
  Road2,
  Road3,
  Spe1,
  Spe2,
  Spe3,
  Spe4
}

enum TrackDesign {
  Left,
  Center,
  Right,
  Up,
  Down,
  O1,
  O2
}
