// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IBolid {
  function Flivver_Bolid_placeCar(string memory nameandkey) external;

  function Flivver_Bolid_moveCar(int32 x, int32 z, int32 dx, int32 dz, int32 ax, int32 az) external;
}
