// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface ILineup {
  function Flivver_Lineup_participate() external returns (uint32);

  function Flivver_Lineup_readyOrNot(string memory nameandkey) external returns (uint32);

  function Flivver_Lineup_starting(string memory nameandkey) external returns (uint64);
}
