// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface ITrackBuild {
  function Flivver_TrackBuild_generateGrid() external view returns (uint32);

  function Flivver_TrackBuild_buildTrack(
    string memory nameandkey,
    uint32 width,
    uint32 height,
    bytes memory grid
  ) external returns (uint32);

  function Flivver_TrackBuild_genRace(string memory nameandkey) external returns (uint32);
}
